apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  MONGO_URI: "mongodb://mp3_user:mp3_password@mongodb:27017/"
  MONGO_VIDEOS_URI: "mongodb://video_user:video_password@mongodb:27017/videos"
  MONGO_MP3S_URI: "mongodb://mp3_user:mp3_password@mongodb:27017/mp3s"
