apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init.js: |
    // Crea il database e l'utente per l'applicazione
    db = db.getSiblingDB('mp3s');
    
    db.createUser({
      user: 'mp3_user',
      pwd: 'mp3_password',
      roles: [
        {
          role: 'readWrite',
          db: 'mp3s'
        }
      ]
    });
    
    // Crea le collezioni se necessario
    db.createCollection('fs.files');
    db.createCollection('fs.chunks');
    
    print('MongoDB initialization completed');