apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init.js: |
    // Crea database per videos
    db = db.getSiblingDB('videos');
    db.createUser({
      user: 'video_user',
      pwd: 'video_password',
      roles: [
        {
          role: 'readWrite',
          db: 'videos'
        },
        {
          role: 'readWrite',
          db: 'mp3s'
        }
      ]
    });
    
    // Crea le collezioni GridFS per videos
    db.createCollection('fs.files');
    db.createCollection('fs.chunks');
    
    // Crea database per mp3s
    db = db.getSiblingDB('mp3s');
    db.createUser({
      user: 'mp3_user',
      pwd: 'mp3_password',
      roles: [
        {
          role: 'readWrite',
          db: 'videos'
        },
        {
          role: 'readWrite',
          db: 'mp3s'
        }
      ]
    });
    
    // Crea le collezioni GridFS per mp3s
    db.createCollection('fs.files');
    db.createCollection('fs.chunks');
    
    print('MongoDB initialization completed');