apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data: 
  definitions.json: |
    {
      "vhosts": [
        { "name": "/" }
      ],
      "queues": [
        {
          "name": "queue1",
          "vhost": "/",
          "durable": true,
          "arguments": {
            "x-queue-type": "classic"
          }
        },
        {
          "name": "queue2",
          "vhost": "/",
          "durable": true,
          "arguments": {
            "x-queue-type": "classic"
          }
        }
      ]
    }